cask_args appdir: '/Applications'

# brew
#brew 'ansible'
brew 'anyenv'
brew 'git'
brew 'mas'
#brew 'pyenv' # switch anyenv

# cask
#cask '1password' # require Rosetta 2
cask 'appcleaner'
#cask 'authy' # require Rosetta 2
cask 'coteditor'
cask 'dropbox' # require Rosetta 2
#cask 'evernote' # require Rosetta 2
cask 'firefox'
cask 'google-chrome'
#cask 'google-japanese-ime' # require Rosetta 2
cask 'iterm2'
cask 'notion'
#cask 'obs' # require Rosetta 2
#cask 'onedrive' # require Rosetta 2
#cask 'slack'
#cask 'vagrant' # require Rosetta 2
#cask 'virtualbox' # require Rosetta 2
cask 'visual-studio-code'
#cask 'homebrew/cask-versions/visual-studio-code-insiders' # switch visual-studio-code
cask 'zoom'

# mas
#mas 'ForkLift', id: 412448059 # require Rosetta 2
#mas 'Todoist', id: 585829637
#mas 'Trello', id: 1278508951 # require Rosetta 2
#mas 'TweetDeck', id: 485812721
#mas 'Twitter', id: 1482454543
